### ISSUE TITLE
No .ioc included with BLE_Peripheral_Lite

### ISSUE THREAD

**Issue by OsciX** [STMicroelectronics/STM32CubeWB0#1]
**Set-up**

* NUCLEO-WB09KE
* STM32CubeIDE 1.16.0

**Describe the bug (skip if none)**

 The BLE_Peripheral_Example compiles fine, and I'm able to see the "HELLO" device in the ST BLE Sensor application. However, I am unable to modify the example because it does not include a .ioc file.

**How to reproduce the bug (skip if none)**

Create a new project, using the BLE_Peripheral_Lite example for the NUCLEO-WB09KE. Use the Project Explorer to open BLE_Peripheral_Lite.ioc , and a generic error is shown. Alternatively, show the file in system explorer, and observe that it does not exist.

**Additional context**

Would it be possible to provide the .ioc file used to configure this example?

**Screenshots**

![image](https://github.com/user-attachments/assets/7f4c3075-4cdb-4c9b-b176-b8acb412bac8)
![image](https://github.com/user-attachments/assets/6fbfdd65-ee37-4c9b-867c-b48c8318005e)

**Comment by RJMSTM** [comment]
ST Internal Reference: 187659

**Comment by RJMSTM** [comment]
Hello,

I hope you are fine. The issue you reported has been fixed in the frame of version v1.1.0 of the STM32CubeWB0 published recently on GitHub. Thank you again for having reported.
