### ISSUE TITLE
Rename driver files to follow usual STM32Cube convention

### ISSUE THREAD

**Issue by erwango** [STMicroelectronics/STM32CubeWB0#2]
**Describe the bug**

STM32WB0 driver files are named [`stm32wb0x_hal_adc.h` ](https://github.com/STMicroelectronics/stm32wb0x_hal_driver/blob/68eda3c0ac7b75d2bd1f3fd9f6bcc21a6e2a0bbd/Inc/stm32wb0x_hal_adc.h) while according to STM32Cube convention is `stm32wb0xx_hal_adc.h` (mind the double `x`).
See for instance [stm32wbaxx_hal_adc.h](https://github.com/STMicroelectronics/stm32wbaxx_hal_driver/blob/43d3c53a56d43aa31ff5c29d797e243cd1ef66b8/Inc/stm32wbaxx_hal_adc.h)

Same for [`cmsis_device_wb0/Include`](https://github.com/STMicroelectronics/cmsis_device_wb0/tree/e546ae5abf9635d22c9472ceddd2131d913a713e/Include) files while aslo miss a `x`

**Impact**

Scripts based environments used to existing STM32Cube convention should add specific treatment for WB0.

**Comment by msmttchr** [comment]
Hello Erwan, is this something to be done by people who are releasing the Cube firmware?
@orazioprivitera

**Comment by erwango** [comment]
> Hello Erwan, is this something to be done by people who are releasing the Cube firmware? @orazioprivitera

I guess, yes.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 189879

**Comment by TOUNSTM** [comment]
Hello @erwango,

We have received feedback from our development teams. Unfortunately, they have indicated that changing the driver/CMSIS naming convention at this stage would significantly impact backward compatibility and incur considerable effort. This change would need to be applied across the Cube SW package drivers, related documentation, and the STM32CubeMX tool integration.

Therefore, they suggest adapting the scripts to handle the single digit for STM32CubeWB0.

Thank you for your understanding.
Best Regards,

**Comment by erwango** [comment]
Thanks for the feedback @TOUNSTM.

From what I understood there was also a good reason to make it this way as STM32WB0 variants use a single digit number (STM32WB07 for instance) while other series use 2 digits for variant naming (STM32WBA55 for instance).
Hence this single `x` makes actual sense and it is not just a fantasy.
We'll adapt our scripts to this possible use case.
