### ISSUE TITLE
Improve documentation for BLE_Transparent

### ISSUE THREAD

**Issue by mringwal** [STMicroelectronics/STM32CubeWB0#3]
The contributing guidelines suggests to raise an issue before creating a pull request, so there we go.

I'd like to improve the documentation for the BLE_Transparent example by:
- documenting the default UART configuration (which is 921600, no flow control), and where to change it.
- explaining how to compile the example without the BLE stack so it can be used with an external Bluetooth Stack.

**Comment by RJMSTM** [comment]
ST Internal Reference: 193799

**Comment by RJMSTM** [comment]
Hello,
I hope you are fine. The issue you reported has been fixed in the frame of version v1.1.0 of the STM32CubeWB0 published recently on GitHub. Thank you again for having reported.

**Comment by mringwal** [comment]
Thanks for update, appreciated!
